Kheirie/urls.py
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from Kheirie import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Kheirie_Home.urls")),
    path('account/', include("Kheirie_Account.urls")),

]

# urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kheirie_Account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import PostLists, PostCreate, PostUpdate, PostDelete, Register, Profile

app_name = "account"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),

    path('logout/', views.LogoutView.as_view(), name='logout'),
    #
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += {
    path('', PostLists.as_view(), name="home"),
    path('post/create', PostCreate.as_view(), name="post-create"),
    path('post/update/<int:pk>', PostUpdate.as_view(), name="post-update"),
    path('post/delete/<int:pk>', PostDelete.as_view(), name="post-delete"),
    path('signup', Register.as_view(), name="signup"),
    path('profile/', Profile.as_view(), name="profile"),

}

Kheirie_Home/urls.py
from django.urls import path
from .views import home, detail, posts

app_name = "home"
urlpatterns = [
    path('', home, name="home"),
    path('detail/<slug:slug>', detail, name="detail"),
    path('posts', posts, name="posts")
]

Kheirie_Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    file = models.FileField(upload_to='documents', verbose_name="آپلود فایل")

Kheirie_Home/models.py
from django.db import models
from django.urls import reverse
from Kheirie_Account.models import User
from django.utils import timezone
from extensions.utils import jalali_converter



class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده')
    )

    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس")
    description = models.TextField(verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر", blank=True)
    video = models.URLField(max_length=500, blank=True)
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now="True")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")

    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")

    def jpublish(self):
        return jalali_converter(self.publish)

Kheirie_Account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Kheirie_Account/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from Kheirie_Home.models import Post
from django.urls import reverse_lazy
from .forms import SignupForm
from .models import User


class PostLists(LoginRequiredMixin, ListView):
    template_name = 'registration/home.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.all()
        else:
            return Post.objects.filter()


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "slug", "description", "thumbnail", "publish", "status"]
    template_name = "registration/post-create-update.html"


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ["title", "slug", "description", "thumbnail", "publish", "status"]
    template_name = "registration/post-create-update.html"


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('account:home')
    template_name = "registration/post-confirm-delete.html"


class Register(CreateView):
    form_class = SignupForm
    template_name = "registration/register.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        return redirect("/account/login")


class Profile(UpdateView):
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'file']
    template_name = "registration/profile.html"
    success_url = reverse_lazy("account:profile")

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

Kheirie_Home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def home(request):
    context = {
        "post": Post.objects.filter(status="p").order_by("-publish")[:3]
    }
    return render(request, 'home.html', context)


def detail(request, slug):
    context = {
        "detail": get_object_or_404(Post, slug=slug, status="p")
    }
    return render(request, 'detail.html', context)


def posts(request):
    context = {
        "post": Post.objects.filter(status="p").order_by("-publish")
    }
    return render(request, 'posts.html', context)

templates/posts.html
{% load static %}
{% load embed_video_tags %}
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="icon" href="{% static "images/favicon2.png" %}" sizes="32x32" type="image/png">
    <title>جامع - المركز الإسلامي  القالب</title>

    <link rel="stylesheet" href="{% static "css/icons.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/fancybox.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.circliful.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/rtl.css" %}">
    <link rel="stylesheet" href="{% static "css/shabnam.css" %}">
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">

    <!-- Color Scheme -->
    <link rel="stylesheet" href="{% static "css/colors/color3.css" %}" title="color" /><!-- Color -->
</head>
<body>
    <main>
        <header class="style1">
            <div class="container">
                <div class="logo"><a href="index-2.html" title="Logo"><img src="{% static "images/logo3.png" %}" alt="logo3.png"></a></div>
                <nav>
                    <div>
                        <ul>
                            <li><a href="{% url "home:posts" %}" title="">اخبار</a></li>
                            <li><a href="{% url "account:signup" %}" title="">ثبت نام</a></li>
                            <li><a href="{% url "account:login" %}" title="">ورود</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </header><!-- Header -->
        <div class="rspn-hdr">
            <div class="lg-mn">
                <div class="logo"><a href="{% url "home:home" %}" title="Logo"> <img src="{% static "images/logo2.png" %}" alt="logo2.png"> </a> </div>
                <div class="rspn-cnt">
                    <span><i class="fa fa-envelope thm-clr"></i><a href="index-2.html#" title=""> info@mail.com </a></span>
                    <span><i class="fa fa-phone thm-clr"></i> 123-456-789 </span>
                </div>
                <span class="rspn-mnu-btn"> <i class="fa fa-list-ul"></i> </span>
            </div>
            <div class="rsnp-mnu">
                <span class="rspn-mnu-cls"> <i class="fa fa-times"></i> </span>
                    <ul>
                            <li><a href="{% url "home:posts" %}" title="">اخبار</a></li>
                            <li><a href="{% url "account:signup" %}" title="">ثبت نام</a></li>
                            <li><a href="{% url "account:login" %}" title="">ورود</a></li>
                    </ul>
            </div><!-- Responsive Menu -->
        </div><!-- Responsive Header -->
        <section>
            <div class="gap remove-bottom black-layer2 opc85">
                <div class="fixed-bg" style="background-image: url({% static "images/parallax12.jpg" %});"></div>
                <div class="container">
                    <div class="page-title-wrap">
                        <h2>گزیده مطالب</h2>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="gap">
                <div class="container">
                    <div class="event-wrap">
                        <div class="row">
                            
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="remove-ext3">
                                    <div class="row">
                                        {% for posts in post %}
                                            <div class="col-md-4 col-sm-6 col-lg-4">
                                                <div class="event-box2">
                                                    <div class="event-thumb">
                                                        <a href="{% url "home:detail" posts.slug %}" title="">
                                                            {% if posts.thumbnail %}
                                                                    <img src="{{ posts.thumbnail.url }}" alt="event-img2-1.jpg">
                                                            {% endif %}
                                                            {% if posts.video %}
                                                            <style>
                                                                    .h_iframe-aparat_embed_frame{position:relative;}.h_iframe-aparat_embed_frame .ratio{display:block;width:100%;height:auto;}.h_iframe-aparat_embed_frame iframe{position:absolute;top:0;left:0;width:100%;height:100%;}
                                                            </style>
                                                            <div class="h_iframe-aparat_embed_frame">
                                                                <span style="display: block;padding-top: 57%"></span>
                                                                <iframe src="{{ posts.video }}"></iframe>
                                                            </div>
                                                            {% endif %}
                                                        </a>
                                                    </div>
                                                    <div class="event-info">
                                                        <h4><a href="{% url "home:detail" posts.slug %}" title="">{{ posts.title|truncatewords:7 }}</a></h4>
                                                        <p>{{ posts.description|truncatewords:30 }}</p>
                                                        <ul class="event-mta">
                                                            <li><i class="flaticon-clock"></i>{{ posts.jpublish }}</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Event Wrap -->
                </div>
            </div>
        </section>
       <footer>
            <div class="gap top-spac70 drk-bg2 remove-bottom">
                <div class="container">
                    <div class="footer-data">
                        <div class="row">
                            <div class="col-md-4 col-sm-12 col-lg-4">
                                <div class="wdgt-box style2">
                                    <div class="logo"><a href="index-2.html" title="Logo"><img src="assets/images/logo2.png" alt="logo2.png"></a></div>
                                    <p>مرکز اسلامی <b>جامعه</b> در سال 1373 با هدف خدمت به جامعه اسلامی تشکیل شده است.</p>
                                </div>
                            </div>
                            <div class="col-md-8 col-sm-12 col-lg-8">
                                <div class="row">
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>لینک های مفید</h4>
                                            <ul>
                                                <li><a href="index-2.html#" title="">بلاگ</a></li>
                                                <li><a href="index-2.html#" title="">خدمات</a></li>
                                                <li><a href="index-2.html#" title="">کمک مالی</a></li>
                                                <li><a href="index-2.html#" title="">تیم</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>صفحات سایت</h4>
                                            <ul>
                                                <li><a href="index-2.html#" title="">صفحه اصلی</a></li>
                                                <li><a href="index-2.html#" title="">مطالب سایت</a></li>
                                                <li><a href="index-2.html#" title="">تالار گفتمان</a></li>
                                                <li><a href="index-2.html#" title="">درباره ما</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-lg-4">
                                        <div class="wdgt-box">
                                            <h4>تماس با ما</h4>
                                            <ul class="cont-lst">
                                                <li><i class="flaticon-location-pin"></i>خیابان مرکزی - بخش اصلی - ساختمان مرکزی - مرکز اسلامی جامعه</li>
                                                <li><i class="flaticon-call"></i>123-456-789</li>
                                                <li><i class="flaticon-email"></i><a href="index-2.html#" title="">info@mail.com</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Footer Data -->
                    <div class="bottom-bar">
                        <p>1398 | تمامی حقوق برای جامعه مفحوظ میباشد</p>
                        <div class="scl">
                            <a href="index-2.html#" title="توییتر" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="index-2.html#" title="اینستاگرام" target="_blank"><i class="fa fa-instagram"></i></a>
                            <a href="index-2.html#" title="گوگل پلاس" target="_blank"><i class="fa fa-google-plus"></i></a>
                            <a href="index-2.html#" title="فیسبوک" target="_blank"><i class="fa fa-facebook"></i></a>
                        </div>
                    </div><!-- Bottom Bar -->
                </div>
            </div>
        </footer>
    </main><!-- Main Wrapper -->

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/downCount.js" %}"></script>
    <script src="{% static "js/fancybox.min.js" %}"></script>
    <script src="{% static "js/isotope.pkgd.min.js" %}"></script>
    <script src="{% static "js/perfectscrollbar.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.circliful.min.js" %}"></script>
    <script src="{% static "js/custom-scripts.js" %}"></script>
</body>	

</html>